apiVersion: v1
kind: Service
metadata:
  name: mlflow-srvc
  labels:
    run: mlflow-srvc
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: mlflow
